services:
  s-expensives__db:
    image: postgres:15
    container_name: s_expensives__db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: s_expensives__db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - s_expensives__network
      
  s-expensives__storage:
    image: minio/minio:latest
    container_name: s_expensives__storage
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: secret123
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - storage_data:/data
    networks:
      - s_expensives__network

volumes:
  db_data:
  storage_data:
networks:
  s_expensives__network:
    driver: bridge